### ISSUE TITLE
Sehen, welcher User gerade einen Artikel/Contentelement bearbeitet

### ISSUE THREAD

**Issue by akroii** [BugBuster1701/contao-online-bundle#6]
Hallo Bugbuster,
es gab früher zu Contao 3-Zeiten eine Erweiterung, bei der man sehen konnte ob ein anderer Backenduser gerade einen Artikel bearbeitet. Das wurde dann über ein kleines Männchen bei den Stift-Icon dargestellt. Besser wäre ein Einstellung, dass man auswählen kann ob ein Artikel/Contentelement gelockt wird oder nur ein Hinweis angezeigt werden soll. So kann man ein versehentliches bearbeiten des Artikels gleich vo vornherein verhindern.

**Comment by BugBuster1701** [comment]
Dann muss diese Contao 3 Erweiterung aktualisiert werden.
Hat mit der hier nichts zu tun.
